/**
 * `npm run economy` — plays Lemon Island headlessly for 30 days under four
 * strategies × 25 seeds with the game's own crowd sim, market and ledger, and
 * writes ECONOMY.md with the results. Deterministic: same code, same numbers.
 */
import fs from "node:fs";
import { simulateIsland, type DayStat, type Strategy } from "../games/lemon/forecast";
import { ROSTER } from "../games/lemon/friends";
import { BUILDS, HELPER_WAGE, BASE_LEMON, IMPACT, SPOIL_SHARE, CUPS_PER_LEMON, START_BALANCE, toRf } from "../games/lemon/economy";

const DAYS = 30, SEEDS = 25;
const RF_SUPPLY = 949_574_971; // RF totalSupply read from Robinhood chain (0x0779…B71f)
const strategies: { name: string; blurb: string; s: Strategy }[] = [
  { name: "Steady", blurb: "prices at the in-game \"good price\", reinvests", s: { priceFactor: 1, builds: true } },
  { name: "Greedy", blurb: "prices 40% above it, reinvests", s: { priceFactor: 1.4, builds: true } },
  { name: "Bargain", blurb: "prices 30% below it, reinvests", s: { priceFactor: 0.7, builds: true } },
  { name: "Saver", blurb: "good price, never builds", s: { priceFactor: 1, builds: false } },
];

const mean = (xs: number[]) => xs.reduce((a, b) => a + b, 0) / xs.length;
const fmt = (n: number, dp = 0) => n.toLocaleString("en-US", { minimumFractionDigits: dp, maximumFractionDigits: dp });

interface Run { days: DayStat[]; long: DayStat[]; last: DayStat; minBal: number; cups: number; wk4: number; bal60: number; }
const runs = new Map<string, Run[]>();
for (const { name, s } of strategies) {
  const list: Run[] = [];
  for (let seed = 1; seed <= SEEDS; seed++) {
    const long = simulateIsland(ROSTER, DAYS * 2, seed * 7919, s);
    const days = long.slice(0, DAYS);
    const last = days[days.length - 1];
    list.push({
      days, long, last,
      minBal: Math.min(...days.map(d => d.balance)),
      cups: days.reduce((a, d) => a + d.cups, 0),
      wk4: days.slice(-7).reduce((a, d) => a + d.sales, 0) / 7,
      bal60: long[long.length - 1].balance,
    });
  }
  runs.set(name, list);
}

const steady = runs.get("Steady")!;
const saver = runs.get("Saver")!;
const avgBal = (rs: Run[], day: number) => mean(rs.map(r => r.long[day - 1].balance));
let crossover = 0;
for (let day = 6; day <= DAYS * 2 && !crossover; day++) if (avgBal(steady, day) > avgBal(saver, day)) crossover = day;
// The median steady run (by RF burned) for the day-by-day table and chart.
const median = [...steady].sort((a, b) => a.last.burned - b.last.burned)[Math.floor(SEEDS / 2)];

const row = (name: string, blurb: string) => {
  const r = runs.get(name)!;
  const brokeDays = r.filter(x => x.minBal < 5).length;
  return `| **${name}** (${blurb}) | ${fmt(mean(r.map(x => x.cups)))} | ${fmt(mean(r.map(x => x.wk4)), 1)} | ${fmt(mean(r.map(x => x.last.stalls)), 1)} | ${fmt(mean(r.map(x => x.last.balance)))} | ${fmt(mean(r.map(x => x.bal60)))} | ${fmt(mean(r.map(x => x.last.burned)))} | ${fmt(mean(r.map(x => x.last.toFriends)))} | ${brokeDays}/${SEEDS} |`;
};

const burn30 = mean(steady.map(x => x.last.burned));
const friends30 = mean(steady.map(x => x.last.toFriends));
const scale = (players: number) => `| ${fmt(players)} | ${fmt(burn30 * players)} RF | ${fmt(friends30 * players)} RF | ${((burn30 * players * 12) / RF_SUPPLY * 100).toFixed(2)}% |`;

const d = median.days;
const chartDays = d.map(x => x.day).join(", ");
const md = `# Lemon Island economy report

Generated by \`npm run economy\` (\`tools/economy-report.ts\`). The simulation plays the **real game code** headlessly: the same crowd sim (\`sim.ts\`), lemon market and ledger (\`economy.ts\`) the game runs, for **${DAYS} days × ${SEEDS} random seeds** per strategy. All RF is simulated demo RF.

## Where RF goes

RF is never minted by the game. Every flow moves RF between players and Friends, or burns it.

| Flow | Rule | Where the RF ends up |
|---|---|---|
| Cups | Friends pay your cup price | Your balance |
| Lemons | Bought on a shared market, ${BASE_LEMON} RF base, +${(IMPACT * 100).toFixed(2)}% per lemon bought today | **50% burned**, 50% to the farmer Friends' wallets |
| Stalls & upgrades | ${BUILDS.map(b => `${b.name} ${b.cost}`).join(" · ")} RF | **50% burned**, 50% to active Friend rewards (the Rare Friends 50/50 rule) |
| Helpers | ${HELPER_WAGE} RF per day for every extra stall's Friend | Straight into the hired Friend's wallet |
| Spoilage | ${SPOIL_SHARE * 100}% of leftover lemons rot overnight | Lost stock: a sink that punishes over-buying |

Start: ${toRf(START_BALANCE)} RF · 1 lemon = ${CUPS_PER_LEMON} cups · a day lasts about 36 seconds.

## Four ways to play (mean of ${SEEDS} seeds; flows over ${DAYS} days)

| Strategy | Cups sold | Daily sales, week 4 | Stalls | Balance day 30 | Balance day 60 | RF burned | RF paid to other Friends | Runs that dipped under 5 RF |
|---|---:|---:|---:|---:|---:|---:|---:|---:|
${strategies.map(x => row(x.name, x.blurb)).join("\n")}

**What this shows**
- **Pricing is a real decision.** Overcharging (Greedy) scares customers off and sells far fewer cups; undercharging (Bargain) sells more but earns less per cup. The in-game "good price" is close to the sweet spot.
- **Investing pays, like a tycoon should.** The Steady builder has less cash while it reinvests, but by week 4 it sells several times more per day, overtakes the Saver's balance on day ${crossover} (average of ${SEEDS} seeds) and ends day 60 ${(avgBal(steady, DAYS * 2) / avgBal(saver, DAYS * 2)).toFixed(1)}× richer.
- **Growth drives the sinks.** The Steady builder burns and pays out far more RF than the Saver, because every stall and upgrade is a 50/50 burn and every extra stall pays a Friend's wages. The more a player succeeds, the more RF they burn.
- **Hard to go broke playing sensibly.** The reserve rule keeps lemon and wage money back before building.

## A typical steady run, day by day (median seed)

\`\`\`mermaid
xychart-beta
  title "Cumulative RF over ${DAYS} days (one steady player)"
  x-axis [${chartDays}]
  y-axis "RF"
  line [${d.map(x => x.burned.toFixed(0)).join(", ")}]
  line [${d.map(x => x.toFriends.toFixed(0)).join(", ")}]
  bar [${d.map(x => Math.max(0, x.balance).toFixed(0)).join(", ")}]
\`\`\`
*Lines: RF burned (lower) and RF paid to other Friends (upper), cumulative. Bars: the player's balance each evening.*

| Day | Weather | Cups | Sales | Profit | Balance | Stalls | Lemon price | Burned (total) | To Friends (total) |
|---:|---|---:|---:|---:|---:|---:|---:|---:|---:|
${d.map(x => `| ${x.day} | ${x.weather} | ${x.cups} | ${x.sales.toFixed(1)} | ${x.profit >= 0 ? "+" : ""}${x.profit.toFixed(1)} | ${x.balance.toFixed(1)} | ${x.stalls} | ${x.lemonPrice.toFixed(2)} | ${x.burned.toFixed(1)} | ${x.toFriends.toFixed(1)} |`).join("\n")}

Negative-profit days are build days: the player spent profit on a new stall or upgrade (half of it burned).

## At scale

One steady player burns about **${fmt(burn30)} RF** and pays about **${fmt(friends30)} RF** to other Friends in ${DAYS} in-game days.

| Players | RF burned per ${DAYS} days | RF paid to Friends per ${DAYS} days | Burned per year, share of RF supply |
|---:|---:|---:|---:|
${[100, 1000, 10000].map(scale).join("\n")}

*RF supply: ${fmt(RF_SUPPLY)} (totalSupply of the RF token on Robinhood chain). The lemon market also rises with total demand, so more players means pricier lemons and more RF burned per cup.*

## Going live

- A shared lemon market contract: price impact from all players' buys, the 50% burn, and 50% streamed to farmer Friends.
- Stall and upgrade payments through the Rare Friends 50/50 gameplay-payment rule.
- Helper wages as direct transfers to the hired Friend's wallet.
- Cup sales from real players' Friends visiting each other's islands.
`;

fs.writeFileSync("ECONOMY.md", md);
console.log(`crossover day ${crossover}`);
console.log(`ECONOMY.md written: steady burn ${fmt(burn30)} RF, to Friends ${fmt(friends30)} RF over ${DAYS} days`);
for (const x of strategies) {
  const r = runs.get(x.name)!;
  console.log(x.name.padEnd(8), "cups", fmt(mean(r.map(y => y.cups))), "wk4", fmt(mean(r.map(y => y.wk4)), 1), "bal30", fmt(mean(r.map(y => y.last.balance))), "bal60", fmt(mean(r.map(y => y.bal60))), "burn", fmt(mean(r.map(y => y.last.burned))), "friends", fmt(mean(r.map(y => y.last.toFriends))), "broke", r.filter(y => y.minBal < 5).length);
}
