/**
 * Pixel-art UI icons (12×12), drawn in code so every platform shows the same
 * crisp icons as the game scene instead of mismatched emoji.
 * Palette keys: k ink · w white · L lemon · M lemon shade · y sun · Y sun shade · c coral · g meadow ·
 * G meadow shade · b pond · l lilac · s signal · o fire · d grey.
 */
import type { ReactElement } from "react";

const COLORS: Record<string, string> = {
  k: "#111111", w: "#ffffff", L: "#F6DE4F", M: "#d6b52e", y: "#F2CE68", Y: "#d9a93a", c: "#ED927E", g: "#B9D984", G: "#7fa653",
  b: "#7DB4DB", l: "#B3A0D8", s: "#CCFF00", o: "#c2481f", d: "#8a8a8a",
};

const ICONS = {
  lemon: [
    "............",
    "............",
    "........ggg.",
    ".......gG...",
    "....kkkk....",
    "..kkLLLLkk..",
    ".kLwwLLLLMk.",
    "kLLwLLLLLLMk",
    ".kLLLLLLLMk.",
    "..kkMMMMkk..",
    "....kkkk....",
    "............",
  ],
  coin: [
    "............",
    "...kkkkkk...",
    "..kyyyyyyk..",
    ".kywyYYyyYk.",
    ".kwyYyyYyYk.",
    ".kyyYyyyyYk.",
    ".kyyYyyyyYk.",
    ".kyyYyyYyYk.",
    ".kyyyYYyyYk.",
    "..kYYYYYYk..",
    "...kkkkkk...",
    "............",
  ],
  flame: [
    ".....k......",
    ".....kk.....",
    "....kcck....",
    "....kcck....",
    "...kccyck...",
    "..kccyycck..",
    "..kcyyyyck..",
    ".kccywwycck.",
    ".kcyywwyyck.",
    ".kcyyyyyyck.",
    "..kccyycck..",
    "...kkkkkk...",
  ],
  cup: [
    ".......k....",
    "......k.....",
    "..kkkkkkkk..",
    "..kwwwwwwk..",
    "..kyyyyyyk..",
    "..kywyyyyk..",
    "...kyyyyk...",
    "...kwyyYk...",
    "...kyyyYk...",
    "...kkkkkk...",
    "............",
    "............",
  ],
  play: [
    "............",
    "..k.........",
    "..kk........",
    "..kkk.......",
    "..kkkk......",
    "..kkkkk.....",
    "..kkkkk.....",
    "..kkkk......",
    "..kkk.......",
    "..kk........",
    "..k.........",
    "............",
  ],
  ffwd: [
    "............",
    "............",
    ".k....k.....",
    ".kk...kk....",
    ".kkk..kkk...",
    ".kkkk.kkkk..",
    ".kkkk.kkkk..",
    ".kkk..kkk...",
    ".kk...kk....",
    ".k....k.....",
    "............",
    "............",
  ],
  people: [
    "............",
    ".kk......kk.",
    ".kkk....kkk.",
    ".kkkkkkkkkk.",
    "kkkkkkkkkkkk",
    "kkwwkkkkwwkk",
    "kkwkkkkkwkkk",
    "kkkkkkkkkkkk",
    "kkkkkwwkkkkk",
    ".kkkkkkkkkk.",
    "..kkkkkkkk..",
    "............",
  ],
  chart: [
    "............",
    ".........kkk",
    ".........kgk",
    ".....kkk.kgk",
    ".....kyk.kgk",
    ".kkk.kyk.kgk",
    ".kck.kyk.kgk",
    ".kck.kyk.kgk",
    ".kck.kyk.kgk",
    "kkkkkkkkkkkk",
    "............",
    "............",
  ],
  sound: [
    "............",
    ".....k......",
    "....kk...k..",
    "...kwk....k.",
    "kkkwwk..k..k",
    "kwwwwk...k.k",
    "kwwwwk...k.k",
    "kkkwwk..k..k",
    "...kwk....k.",
    "....kk...k..",
    ".....k......",
    "............",
  ],
  mute: [
    "............",
    ".....k......",
    "....kk......",
    "...kwk......",
    "kkkwwk.k...k",
    "kwwwwk..k.k.",
    "kwwwwk...k..",
    "kkkwwk..k.k.",
    "...kwk.k...k",
    "....kk......",
    ".....k......",
    "............",
  ],
  waves: [
    "............",
    "............",
    "..kk....kk..",
    ".k..k..k..k.",
    "k....kk....k",
    "............",
    "..kk....kk..",
    ".k..k..k..k.",
    "k....kk....k",
    "............",
    "............",
    "............",
  ],
  still: [
    "............",
    "............",
    "............",
    "............",
    "kkkkkkkkkkkk",
    "............",
    "............",
    "............",
    "kkkkkkkkkkkk",
    "............",
    "............",
    "............",
  ],
  sun: [
    ".....kk.....",
    ".k...kk...k.",
    "..k......k..",
    "....kkkk....",
    "...kyyyyk...",
    "kk.kywyyk.kk",
    "kk.kyyyYk.kk",
    "...kyyYYk...",
    "....kkkk....",
    "..k......k..",
    ".k...kk...k.",
    ".....kk.....",
  ],
  hot: [
    ".....kk.....",
    ".k...kk...k.",
    "..k......k..",
    "....kkkk....",
    "...kcccck...",
    "kk.kcycck.kk",
    "kk.kcccck.kk",
    "...kccook...",
    "....kkkk....",
    "..k......k..",
    ".k...kk...k.",
    ".....kk.....",
  ],
  cloud: [
    "............",
    "............",
    "....kkk.....",
    "...kwwwk....",
    ".kkwwwwwkk..",
    "kwwwwwwwwwk.",
    "kwwwwwwwwwwk",
    "kwwwwwwwwwwk",
    ".kkkkkkkkkk.",
    "............",
    "............",
    "............",
  ],
  rain: [
    "....kkk.....",
    "...kdddk....",
    ".kkdddddkk..",
    "kddddddddddk",
    "kddddddddddk",
    ".kkkkkkkkkk.",
    "............",
    "..b...b...b.",
    ".b...b...b..",
    "............",
    "...b...b....",
    "..b...b.....",
  ],
  star: [
    ".....kk.....",
    ".....kk.....",
    "....kllk....",
    "kkkkkllkkkkk",
    ".kllllllllk.",
    "..kllllllk..",
    "...kllllk...",
    "..kllkkllk..",
    ".kllk..kllk.",
    ".kkk....kkk.",
    "............",
    "............",
  ],
  happy: [
    "...kkkkkk...",
    "..kyyyyyyk..",
    ".kyyyyyyyyk.",
    "kyykyyyykyyk",
    "kyykyyyykyyk",
    "kyyyyyyyyyyk",
    "kyykyyyykyyk",
    "kyyykkkkyyyk",
    ".kyyyyyyyyk.",
    "..kyyyyyyk..",
    "...kkkkkk...",
    "............",
  ],
  meh: [
    "...kkkkkk...",
    "..kyyyyyyk..",
    ".kyyyyyyyyk.",
    "kyykyyyykyyk",
    "kyykyyyykyyk",
    "kyyyyyyyyyyk",
    "kyyyyyyyyyyk",
    "kyykkkkkkyyk",
    ".kyyyyyyyyk.",
    "..kyyyyyyk..",
    "...kkkkkk...",
    "............",
  ],
  angry: [
    "...kkkkkk...",
    "..kcccccck..",
    ".kckcccckck.",
    "kccckcckccck",
    "kcckcccckcck",
    "kcccccccccck",
    "kccckkkkccck",
    "kcckcccckcck",
    ".kcccccccck.",
    "..kcccccck..",
    "...kkkkkk...",
    "............",
  ],
  // Buildings
  stand: [
    "............",
    "kkkkkkkkkkkk",
    "kywywywywywk",
    "kywywywywywk",
    "kkkkkkkkkkkk",
    ".k........k.",
    ".k........k.",
    "kkkkkkkkkkkk",
    "kwwwwwwwwwwk",
    "kcccccccccck",
    "kwwwwwwwwwwk",
    "kkkkkkkkkkkk",
  ],
  cart: [
    "............",
    ".kkkkkkkkkk.",
    ".kbwbwbwbwk.",
    ".kkkkkkkkkk.",
    "..k......k..",
    "..k......k..",
    ".kkkkkkkkkk.",
    ".kwwwwwwwwk.",
    ".kbbbbbbbbk.",
    ".kkkkkkkkkk.",
    "..kwk..kwk..",
    "...k....k...",
  ],
  bar: [
    ".........k..",
    "........k...",
    "..kkkkkkkk..",
    "..kwwwwwwk..",
    "..kllllllk..",
    "..klwllllk..",
    "...kllllk...",
    "...kllllk...",
    "....kllk....",
    ".....kk.....",
    ".....kk.....",
    "...kkkkkk...",
  ],
  umbrella: [
    ".....kk.....",
    "...kkllkk...",
    "..klwllwlk..",
    ".klwwllwwlk.",
    "kllwwllwwllk",
    "kkkkkkkkkkkk",
    ".....kk.....",
    ".....kk.....",
    ".....kk.....",
    ".....kk..k..",
    "......kkk...",
    "............",
  ],
  jug: [
    "............",
    ".kkkkkkk....",
    "..kwwwwkkk..",
    "..kyyyyk.k..",
    "..kywyyk..k.",
    "..kyyyyk..k.",
    "..kyyyyk.k..",
    "..kyyyyykk..",
    "..kyyyyYk...",
    "..kyyyYYk...",
    "..kkkkkkk...",
    "............",
  ],
  sign: [
    "............",
    "............",
    "kkkkkkkkkkkk",
    "kssssssssssk",
    "kskkskkskksk",
    "kssssssssssk",
    "kkkkkkkkkkkk",
    "...k....k...",
    "...k....k...",
    "...k....k...",
    "..kkk..kkk..",
    "............",
  ],
  farm: [
    "...kkkkkk...",
    "..kggggggk..",
    ".kgyggggygk.",
    "kggggggGgggk",
    "kgygggggyggk",
    ".kgggyggGgk.",
    "..kkkkkkkk..",
    ".....kk.....",
    ".....kk.....",
    ".....kk.....",
    "...kkkkkk...",
    "............",
  ],
  balloon: [
    "...kkkkkk...",
    "..kcwcwcwk..",
    ".kcwcwcwcwk.",
    ".kcwcwcwcwk.",
    ".kcwcwcwcwk.",
    "..kcwcwcwk..",
    "...kkkkkk...",
    "...k....k...",
    "....k..k....",
    "....kkkk....",
    "....kyyk....",
    "....kkkk....",
  ],
} satisfies Record<string, string[]>;

export type IconName = keyof typeof ICONS;

const cache = new Map<IconName, ReactElement[]>();
function rectsFor(name: IconName): ReactElement[] {
  let rects = cache.get(name);
  if (rects) return rects;
  rects = [];
  ICONS[name].forEach((row, y) => {
    let x = 0;
    while (x < row.length) {
      const ch = row[x];
      let end = x + 1;
      while (end < row.length && row[end] === ch) end++;
      if (ch !== ".") rects!.push(<rect key={`${x}.${y}`} x={x} y={y} width={end - x} height={1} fill={COLORS[ch] ?? "#111111"} />);
      x = end;
    }
  });
  cache.set(name, rects);
  return rects;
}

/** A crisp pixel icon. Decorative: always hidden from assistive tech (pair it with text). */
export function Px({ name, size = 16, className }: { name: IconName; size?: number; className?: string }) {
  return (
    <svg className={className ? `li-px ${className}` : "li-px"} viewBox="0 0 12 12" width={size} height={size} shapeRendering="crispEdges" aria-hidden="true" focusable="false">
      {rectsFor(name)}
    </svg>
  );
}

export const WEATHER_ICON = { sunny: "sun", hot: "hot", cloudy: "cloud", rain: "rain", festival: "star" } as const satisfies Record<string, IconName>;

/** Dev check: every icon is exactly 12×12 with known palette keys. */
export function iconProblems(): string[] {
  const out: string[] = [];
  for (const [name, rows] of Object.entries(ICONS)) {
    if (rows.length !== 12) out.push(`${name}: ${rows.length} rows`);
    rows.forEach((r, i) => {
      if (r.length !== 12) out.push(`${name}[${i}]: ${r.length} cols`);
      for (const ch of r) if (ch !== "." && !COLORS[ch]) out.push(`${name}[${i}]: bad key ${ch}`);
    });
  }
  return out;
}
